    using UnityEngine;

    namespace Truchet
    {
        // TODO ROADMAP:
        // [x] Mesh-based composition result container
        // [ ] Add submesh support
        // [ ] Add material indexing
        // [ ] Add bounds caching
        // [ ] Add chunked mesh support
        // [ ] Add GPU buffer conversion helpers
        // [ ] Add adjacency metadata (for dual contouring, MS variants)
        // [ ] Add LOD metadata


        /// <summary>
        /// Represents geometry generated by a composition strategy.
        ///
        /// This is typically produced by:
        /// - MarchingSquaresCompositionStrategy
        /// - Future DualContouringCompositionStrategy
        /// - Any field-based mesh generator
        ///
        /// IMPORTANT:
        /// This class does NOT generate geometry.
        /// It is a pure data container.
        ///
        /// Responsibilities:
        /// - Store mesh reference
        /// - Optionally store resolution / metadata
        /// - Provide future extension points
        ///
        /// It must NOT:
        /// - Know about layout
        /// - Know about tiles
        /// - Know about rendering APIs
        /// - Contain marching squares logic
        /// </summary>
        public class MeshCompositionResult : ICompositionResult
        {
            /// <summary>
            /// Generated mesh.
            /// 
            /// Typically:
            /// - Entire grid mesh
            /// - Or a chunked region mesh
            /// </summary>
            public Mesh Mesh;

            /// <summary>
            /// Logical resolution of the composed field.
            /// 
            /// Example:
            /// - Grid resolution for Marching Squares
            /// - Scalar field resolution
            ///
            /// This is metadata only.
            /// Renderer may use it for bounds calculation.
            /// </summary>
            public int Resolution;

            /// <summary>
            /// World-space bounds of the generated mesh.
            ///
            /// Composition layer should set this.
            /// Renderer may use it for culling.
            /// </summary>
            public Bounds Bounds;

            /// <summary>
            /// Indicates whether this mesh was generated from:
            /// - SDF field
            /// - Discrete mask field
            ///
            /// Pure metadata.
            /// </summary>
            public bool FromSDF;

            public MeshCompositionResult(
                Mesh mesh,
                int resolution,
                Bounds bounds,
                bool fromSdf)
            {
                Mesh = mesh;
                Resolution = resolution;
                Bounds = bounds;
                FromSDF = fromSdf;
            }
        }
    }